apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: tp04-2
  namespace: my-namescpace
  labels:
    MyApp: tp04-2
spec:
  replicas: 4
  selector:
    matchLabels:
      tier: tp04-2
  template:
    metadata:
      labels:
        tier: tp04-2
    spec:
      containers:
      - name: tp04-2
        image: registry.cluster.wik.cloud/public/echo
        ports:
        - containerPort: 8080